version: '3.0'

services:

  P3:
    restart: always
    build: ./P3
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b :8000 practica3:app


  nginx:
    restart: always
    build: ./nginx
    ports:
      - "5000:5000"
    depends_on:
      - P3
